version: "3.0"
networks:
  service-net:
services:
  traefik:
    image: "traefik:v2.5"
    networks:
      - service-net
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8070:8070"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  strapi:
    image: "ditmar/strapi-cms:${STRAPI_APP}"
    networks:
      - service-net
    labels:
      - "traefik.enable=true"
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      - APP_KEYS=O/gLZDV0HZOz7i7k0LeDGg==,v0Awz6h/KgWCcGaCvK8BFQ==,Nlymi8OjzaAxVn/SwfrKMQ==,9A6JTTBeWlu97L4p9mf/3Q==
      - API_TOKEN_SALT=SLKpvVBYKFYQPhG8i+8CNA==
      - ADMIN_JWT_SECRET=F4FzU1Ut7CLFyAPrxVffsw==
      - TRANSFER_TOKEN_SALT=u8HVzYYynUiGyn3qsf+GqA==
      - JWT_SECRET=zdgfvkLbay1bDyCPol7KOg==
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=secretpassword321
      - DATABASE_SSL=false
      - PUBLIC_URL=http://revista.repositoriounipol.com:1337
      - STRAPI_ADMIN_BACKEND_URL=http://revista.repositoriounipol.com:1337
      - HOST=0.0.0.0
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads

    restart: always
  webapp:
    image: "ditmar/magazine-spa:e2e817b"
    networks:
      - service-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=Host(`revista.repositoriounipol.com`)"
      - "traefik.http.routers.webapp.entrypoints=web"
    environment:
      - NODE_ENV=production
      - REACT_APP_STRAPI_SERVER_PORT=1337
      - REACT_APP_STRAPI_SERVER=http://revista.repositoriounipol.com
      - REACT_APP_STRAPI_SERVER_SERVICE=api
    restart: always
  postgres:
    image: postgres:13
    networks:
      - service-net
    container_name: my_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword321
      POSTGRES_DB: strapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: