version: "3.0"
networks:
  service-net:
services:
  strapi:
    image: "unipolrepositorio/cms:${STRAPI_APP}"
    networks:
      - service-net
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      - APP_KEYS=O/gLZDV0HZOz7i7k0LeDGg==,v0Awz6h/KgWCcGaCvK8BFQ==,Nlymi8OjzaAxVn/SwfrKMQ==,9A6JTTBeWlu97L4p9mf/3Q==
      - API_TOKEN_SALT=SLKpvVBYKFYQPhG8i+8CNA==
      - ADMIN_JWT_SECRET=F4FzU1Ut7CLFyAPrxVffsw==
      - TRANSFER_TOKEN_SALT=u8HVzYYynUiGyn3qsf+GqA==
      - JWT_SECRET=zdgfvkLbay1bDyCPol7KOg==
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=false
      - PUBLIC_URL=https://revista.repositoriounipol.com/content
      - STRAPI_ADMIN_BACKEND_URL=https://revista.repositoriounipol.com/content
      - HOST=0.0.0.0
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - /home/ubuntu/files:/app/public/uploads

    restart: always
  webapp:
    image: "unipolrepositorio/magazine:${WEB_APP}"
    networks:
      - service-net
    environment:
      - NODE_ENV=production
      - PORT=80
      - DOMAIN_NAME=https://revista.repositoriounipol.com
      - REACT_APP_STRAPI_SERVER_PORT=1337
      - REACT_APP_STRAPI_SERVER=https://revista.repositoriounipol.com/content
      - REACT_APP_STRAPI_SERVER_SERVICE=api
      - REACT_APP_FACEBOOK_URI=https://www.facebook.com/sharer/sharer.php
      - REACT_APP_WHATSAPP_URI=https://api.whatsapp.com/send
      - REACT_APP_TELEGRAM_URI=https://t.me/share/url
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: always
  certbot:
    image: certbot/certbot
    depends_on:
      - webapp
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email your-ditmarcastro@gmail.com --agree-tos --no-eff-email -d revista.repositoriounipol.com
  postgres:
    image: postgres:13
    networks:
      - service-net
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - deployment_postgres_data:/var/lib/postgresql/data
volumes:
  deployment_postgres_data:
    external: true
